[project]
name = "turn-angle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.7.2",
    "plotnine>=0.15.0",
    "polars>=1.34.0",
    "pyarrow>=21.0.0",
    "pymc>=5.25.1",
    "ruff>=0.13.3",
]

[tool.ruff]
line-length = 88
extend-ignore = ["E203"]
# explicitly include .qmd files
include = ["**/*.py", "**/*.qmd"]
